spring.application.name=simple-mcp-server

spring.ai.mcp.server.stdio=true

spring.ai.mcp.server.name=ticketing-tool
spring.ai.mcp.server.version=0.0.21


spring.main.web-application-type=none
spring.main.banner-mode=off
logging.pattern.console=
logging.file.name=./logs/app.log
